/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/audit/{target_type}/{target_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * GET /v1/audit/{target_type}/{target_id}
         * @description Read contract. Use X-Aletheia-Contract: memory-read-v1 for canonical input validation and limits. Legacy coercions and extension inputs remain accepted without that header. Ranked/nested lists are bounded, not exhaustive pagination; no cursor.
         */
        get: operations["getAudit"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /v1/auth/me */
        get: operations["getCurrentPrincipal"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/claims/{claim_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * GET /v1/claims/{claim_id}
         * @description Read contract. Use X-Aletheia-Contract: memory-read-v1 for canonical input validation and limits. Legacy coercions and extension inputs remain accepted without that header. Ranked/nested lists are bounded, not exhaustive pagination; no cursor.
         */
        get: operations["getClaim"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/claims/{claim_id}/explain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * GET /v1/claims/{claim_id}/explain
         * @description Read contract. Use X-Aletheia-Contract: memory-read-v1 for canonical input validation and limits. Legacy coercions and extension inputs remain accepted without that header. Ranked/nested lists are bounded, not exhaustive pagination; no cursor.
         */
        get: operations["explainClaim"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/compatibility/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /v1/compatibility/report */
        get: operations["getCompatibility"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/context": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * POST /v1/context
         * @description Read contract. Use X-Aletheia-Contract: memory-read-v1 for canonical input validation and limits. Legacy coercions and extension inputs remain accepted without that header. Ranked/nested lists are bounded, not exhaustive pagination; no cursor.
         */
        post: operations["createContext"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/context-pack": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * POST /v1/context-pack
         * @description Read contract. Use X-Aletheia-Contract: memory-read-v1 for canonical input validation and limits. Legacy coercions and extension inputs remain accepted without that header. Ranked/nested lists are bounded, not exhaustive pagination; no cursor.
         */
        post: operations["createContextPack"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/dashboard/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * GET /v1/dashboard/overview
         * @description Read contract. Use X-Aletheia-Contract: memory-read-v1 for canonical input validation and limits. Legacy coercions and extension inputs remain accepted without that header. Ranked/nested lists are bounded, not exhaustive pagination; no cursor.
         */
        get: operations["getOverview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /v1/health */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/openapi.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /v1/openapi.json */
        get: operations["getOpenApi"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /v1/ready */
        get: operations["getReadiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/remember": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * POST /v1/remember
         * @description agent-onboarding-v1 creates candidates only, with explicit operation keys and atomic replay. Legacy unconditioned active/candidate writes remain available with their existing permissions. Extension fields remain accepted; supplied review revisions are refused.
         */
        post: operations["rememberCandidate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/retrieve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * POST /v1/retrieve
         * @description Read contract. Use X-Aletheia-Contract: memory-read-v1 for canonical input validation and limits. Legacy coercions and extension inputs remain accepted without that header. Ranked/nested lists are bounded, not exhaustive pagination; no cursor.
         */
        post: operations["retrieveMemory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * POST /v1/search
         * @description Read contract. Use X-Aletheia-Contract: memory-read-v1 for canonical input validation and limits. Legacy coercions and extension inputs remain accepted without that header. Ranked/nested lists are bounded, not exhaustive pagination; no cursor.
         */
        post: operations["searchMemory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /v1/version */
        get: operations["getVersion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AuditClaimLink: {
            claim_id: string;
            created_at: string;
            relation: string;
        };
        AuditRecord: {
            action: string;
            created_at: string;
            /**
             * @description Unclassified free-form audit details are redacted.
             * @constant
             */
            details: "{}";
            id: string;
            namespace: string;
            target_id: string;
            target_type: string;
        };
        CandidateClaim: {
            candidate_status: string;
            contradiction_risk: number;
            created_at: string;
            duplicate_risk: number;
            evidence_ids: string[];
            evidence_spans: components["schemas"]["EvidenceSpan"][];
            extraction_run_id: string;
            id: string;
            memory_type: string;
            metadata: {
                [key: string]: unknown;
            };
            namespace: string;
            object: string;
            predicate: string;
            privacy_level: string;
            subject: string;
            suggested_categories: string[];
            suggested_confidence: number;
            suggested_entities: string[];
            suggested_half_life_days: number | null;
            suggested_importance: number;
            suggested_scope: {
                [key: string]: unknown;
            } | null;
        };
        Claim: {
            confidence_base: number;
            confidence_effective: number;
            created_at: string;
            evidence_ids: string[];
            half_life_days: number;
            id: string;
            importance: number;
            last_accessed_at: string | null;
            last_verified_at: string | null;
            memory_type: string;
            namespace: string;
            object: string;
            predicate: string;
            status: string;
            subject: string;
            valid_from: string | null;
            valid_to: string | null;
            volatility: string;
        };
        ClaimEnvelope: {
            data: components["schemas"]["Claim"];
            pagination?: null;
            request_id: string;
            warnings: string[];
        };
        ClaimHistory: {
            changed_by: string | null;
            claim_id: string;
            created_at: string;
            id: string;
            namespace: string;
            new_status: string;
            old_status: string | null;
            reason: string | null;
        };
        ClaimRelationship: {
            confidence: number;
            created_at: string;
            id: string;
            namespace: string;
            reason: string | null;
            relationship_type: string;
            source_claim_id: string;
            target_claim_id: string;
        };
        ClaimScope: {
            applies_when: string | null;
            claim_id: string;
            created_at: string;
            id: string;
            namespace: string;
            reason: string;
            scope_type: string;
            valid_from: string | null;
            valid_to: string | null;
        };
        CompatibilityEntry: {
            aletheia_max_version: string | null;
            aletheia_min_version: string;
            component_name: string;
            component_type: string;
            component_version: string;
            id: string;
            metadata: {
                [key: string]: unknown;
            };
            notes: string | null;
            status: string;
            tested_at: string | null;
        };
        CompatibilityPlugin: {
            disabled_at: string | null;
            display_name: string;
            enabled_at: string | null;
            external_network_access: boolean;
            id: string;
            install_path: string;
            installed_at: string;
            metadata: {
                [key: string]: unknown;
            };
            name: string;
            permissions_required: string[];
            plugin_manifest_id: string;
            plugin_type: string;
            status: string;
            trust_level: string;
            version: string;
        };
        CompatibilityReport: {
            /**
             * @deprecated
             * @description Historical expected-schema version for the 1.3.1 SDK; not software version.
             */
            aletheia_version: string;
            /** @constant */
            api_version: "v1";
            archive_formats: string[];
            deprecated_fields: {
                aletheia_version: string;
            };
            matrix: components["schemas"]["CompatibilityEntry"][];
            migration_support: {
                from: string;
                safe: boolean;
                to: string;
            };
            platform: string | null;
            plugins: components["schemas"]["CompatibilityPlugin"][];
            python_version: string | null;
            schema_version: string;
            sdk_versions: components["schemas"]["SDKRelease"][];
            service_identity: string;
            software_version: string;
            sqlite_version: string | null;
            supported_features: string[];
            supported_profiles: string[];
            warnings: string[];
        };
        CompatibilityReportEnvelope: {
            data: components["schemas"]["CompatibilityReport"];
            pagination?: null;
            request_id: string;
            warnings: string[];
        };
        ConfidenceSnapshot: {
            age_days: number;
            base_confidence: number;
            claim_id: string;
            computed_at: string;
            contradiction_factor: number;
            decay_factor: number;
            effective_confidence: number;
            explanation: string | null;
            feedback_factor: number;
            half_life_days: number;
            retrieval_salience: number;
            source_reliability_factor: number;
            truth_confidence: number;
            verification_factor: number;
        };
        Conflict: {
            active_claim_id: string | null;
            claim_ids: string[];
            created_at: string;
            id: string;
            namespace: string;
            predicate: string;
            resolution_note: string | null;
            resolved_at: string | null;
            status: string;
            subject: string;
        };
        ConflictFamily: {
            active_claim_id: string | null;
            claim_ids: string[];
            conflict_type: string;
            created_at: string;
            id: string;
            namespace: string;
            predicate: string | null;
            resolution_note: string | null;
            resolution_strategy: string | null;
            resolved_at: string | null;
            status: string;
            subject: string | null;
            updated_at: string;
        };
        ContextItem: {
            abstraction_level: number | null;
            claim_id: string;
            confidence_effective: number;
            /** @description Unclassified derivation graphs are redacted; use typed provenance. */
            derivation: null;
            evidence_ids: string[];
            inference_id: string | null;
            is_inferred: boolean;
            is_reflected: boolean;
            is_stale: boolean;
            memory_type: string;
            reason: string;
            reflection_id: string | null;
            scope: string | null;
            source_kind: string;
            status: string;
            text: string;
        };
        ContextRequest: {
            /** @default false */
            include_derivation_metadata?: boolean;
            /** @default false */
            include_inferences?: boolean;
            /** @default true */
            include_reflections?: boolean;
            namespace: string;
            policy_version_id?: string | null;
            project_id?: string | null;
            /** @default  */
            query?: string;
            /** @default false */
            record_usage?: boolean;
            /**
             * @default hybrid
             * @enum {string}
             */
            retrieval_mode?: "lexical" | "semantic" | "hybrid";
            session_id?: string | null;
            /** @default 1500 */
            token_budget?: number;
        } & {
            [key: string]: unknown;
        };
        ContextWarning: {
            claim_ids: string[];
            conflict_ids: string[];
            text: string;
            warning_type: string;
        };
        CurrentPrincipal: {
            /** @constant */
            api_version: "v1";
            authenticated: boolean;
            /** @enum {unknown} */
            authentication_mode: "bearer" | "console_session" | "local_tokenless";
            capabilities: ("memory:admin" | "memory:audit" | "memory:context" | "memory:delete" | "memory:evaluate" | "memory:extract" | "memory:federation" | "memory:feedback" | "memory:ingest" | "memory:jobs" | "memory:learn" | "memory:peers" | "memory:policy" | "memory:read" | "memory:remote_active_write" | "memory:remote_admin" | "memory:remote_write" | "memory:review" | "memory:revoke_peer" | "memory:share" | "memory:share_sensitive" | "memory:sync" | "memory:sync_secret" | "memory:workspace" | "memory:write_active" | "memory:write_candidate")[];
            expires_at: string | null;
            granted_capabilities: ("memory:admin" | "memory:audit" | "memory:context" | "memory:delete" | "memory:evaluate" | "memory:extract" | "memory:federation" | "memory:feedback" | "memory:ingest" | "memory:jobs" | "memory:learn" | "memory:peers" | "memory:policy" | "memory:read" | "memory:remote_active_write" | "memory:remote_admin" | "memory:remote_write" | "memory:review" | "memory:revoke_peer" | "memory:share" | "memory:share_sensitive" | "memory:sync" | "memory:sync_secret" | "memory:workspace" | "memory:write_active" | "memory:write_candidate")[];
            namespace_grants: string[];
            principal: components["schemas"]["Principal"] | null;
            /** @enum {unknown} */
            privacy_ceiling: "public" | "personal" | "private" | "sensitive" | "secret";
            service_identity: string;
            software_version: string;
            supported_features: string[];
            supported_profiles: string[];
        };
        CurrentPrincipalEnvelope: {
            data: components["schemas"]["CurrentPrincipal"];
            pagination?: null;
            request_id: string;
            warnings: string[];
        };
        ErrorEnvelope: {
            error: {
                /** @enum {string} */
                code: "unauthorized" | "forbidden" | "not_found" | "validation_error" | "conflict" | "integrity_gate_failed" | "stale_schema" | "rate_limited" | "idempotency_conflict" | "payload_too_large" | "unsupported_operation" | "internal_error" | "precondition_required" | "stale_revision" | "review_conflict" | "stale_cursor" | "invalid_cursor" | "unsupported_contract" | "review_scan_limit" | "database_busy" | "replay_result_changed";
                details: Record<string, never>;
                message: string;
            };
            request_id: string;
        };
        EvidenceEvent: {
            content: string;
            content_hash: string;
            created_at: string;
            id: string;
            namespace: string;
            observed_at: string | null;
            privacy_level: string;
            retention_policy: string;
            session_id: string | null;
            source_type: string;
            source_uri: string | null;
            trust_level: string;
        };
        EvidenceSpan: {
            created_at: string | null;
            end_char: number;
            evidence_id: string;
            id: string | null;
            role: string;
            start_char: number;
            text: string;
        };
        ExtractionAuditDecision: {
            candidate_id: string;
            created_at: string;
            decision: string;
            edits_json: null;
            id: string;
            namespace: string;
            reason: string;
            reviewer: string;
        };
        Health: {
            /** @constant */
            api_version: "v1";
            auth_required: boolean;
            database: string;
            schema_version: string;
            service_identity: string;
            service_version: string;
            software_version: string;
            /** @enum {unknown} */
            status: "ok" | "degraded";
            supported_features: string[];
            supported_profiles: string[];
            warnings: string[];
        };
        HealthEnvelope: {
            data: components["schemas"]["Health"];
            pagination?: null;
            request_id: string;
            warnings: string[];
        };
        LegacyReviewRequest: {
            reason: string;
        } & {
            [key: string]: unknown;
        };
        OpenApiDocument: {
            components: {
                [key: string]: unknown;
            };
            info: {
                title: string;
                version: string;
            } & {
                [key: string]: unknown;
            };
            openapi: string;
            paths: {
                [key: string]: unknown;
            };
            security: {
                [key: string]: string[];
            }[];
        } & {
            [key: string]: unknown;
        };
        OpenApiDocumentEnvelope: {
            data: components["schemas"]["OpenApiDocument"];
            pagination?: null;
            request_id: string;
            warnings: string[];
        };
        Overview: {
            candidates: components["schemas"]["CandidateClaim"][];
            conflicts: components["schemas"]["ConflictFamily"][];
            health: components["schemas"]["OverviewHealth"];
            jobs: unknown[];
            metrics: components["schemas"]["OverviewMetrics"];
            review_tasks: components["schemas"]["ReviewTask"][];
            service_requests: unknown[];
            unavailable_sections: ("jobs" | "service_requests" | "review_tasks" | "candidates")[];
        };
        OverviewEnvelope: {
            data: components["schemas"]["Overview"];
            pagination?: null;
            request_id: string;
            warnings: string[];
        };
        OverviewHealth: {
            generated_at: string;
            id: string;
            metrics: components["schemas"]["OverviewMetrics"];
            namespace: string;
            project_id: string | null;
            recommendations: string[];
            warnings: string[];
        };
        OverviewMetrics: {
            active_claim_count: number;
            candidate_count: number | null;
            core_memory_count: number;
            critical_review_task_count: number | null;
            open_review_task_count: number | null;
            pending_review_count: number | null;
            project_id: string | null;
            stale_claim_count: number;
            unresolved_conflict_count: number;
        };
        Principal: {
            /** @enum {unknown} */
            client_type: "admin" | "agent" | "cli" | "mcp" | "sdk" | "test" | "unknown" | "worker";
            id: string;
            name: string;
        };
        ReadAudit: {
            audit: components["schemas"]["AuditRecord"][];
            claim: components["schemas"]["Claim"];
            conflicts: components["schemas"]["Conflict"][];
            evidence: components["schemas"]["EvidenceEvent"][];
            requested_target_type: string;
            target_id: string;
            /** @constant */
            target_type: "claim";
        } | {
            audit: components["schemas"]["AuditRecord"][];
            candidate: components["schemas"]["CandidateClaim"];
            claim_links: components["schemas"]["AuditClaimLink"][];
            decisions: components["schemas"]["ExtractionAuditDecision"][];
            evidence: components["schemas"]["EvidenceEvent"][];
            requested_target_type: string;
            target_id: string;
            /** @constant */
            target_type: "candidate_claim";
        } | {
            audit: components["schemas"]["AuditRecord"][];
            evidence: components["schemas"]["EvidenceEvent"];
            requested_target_type: string;
            target_id: string;
            /** @constant */
            target_type: "evidence";
        };
        ReadAuditEnvelope: {
            data: components["schemas"]["ReadAudit"];
            pagination?: null;
            request_id: string;
            warnings: string[];
        };
        ReadClaimExplanation: {
            audit: components["schemas"]["AuditRecord"][];
            claim: components["schemas"]["Claim"];
            claim_id: string;
            confidence: components["schemas"]["ConfidenceSnapshot"] | null;
            conflicts: components["schemas"]["Conflict"][];
            evidence: components["schemas"]["EvidenceEvent"][];
            history: components["schemas"]["ClaimHistory"][];
            relationships: components["schemas"]["ClaimRelationship"][];
            scopes: components["schemas"]["ClaimScope"][];
        };
        ReadClaimExplanationEnvelope: {
            data: components["schemas"]["ReadClaimExplanation"];
            pagination?: null;
            request_id: string;
            warnings: string[];
        };
        ReadContextPack: {
            access_warnings?: string[];
            context_pack_id: string;
            items: components["schemas"]["ContextItem"][];
            markdown: string;
            policy: {
                context_policy_version_id: string | null;
                ranking_policy_version_id: string | null;
            };
            provenance: components["schemas"]["ReadProvenance"][];
            sections: {
                core_memory: components["schemas"]["ContextItem"][];
                procedural_memory: components["schemas"]["ContextItem"][];
                project_memory: components["schemas"]["ContextItem"][];
                reflections: components["schemas"]["ContextItem"][];
                relevant_memory: components["schemas"]["ContextItem"][];
                session_memory: components["schemas"]["ContextItem"][];
                warnings: components["schemas"]["ContextWarning"][];
            };
            warnings: components["schemas"]["ContextWarning"][];
        };
        ReadContextPackEnvelope: {
            data: components["schemas"]["ReadContextPack"];
            pagination?: null;
            request_id: string;
            warnings: string[];
        };
        ReadProvenance: {
            claim_id: string;
            evidence_ids: string[];
            source_kind: string;
            target_id: string;
        };
        Readiness: {
            /** @constant */
            api_version: "v1";
            auth_required: boolean;
            database: string;
            ready: boolean;
            schema_version: string;
            service_identity: string;
            service_version: string;
            software_version: string;
            /** @enum {unknown} */
            status: "ok" | "degraded";
            supported_features: string[];
            supported_profiles: string[];
            warnings: string[];
        };
        ReadinessEnvelope: {
            data: components["schemas"]["Readiness"];
            pagination?: null;
            request_id: string;
            warnings: string[];
        };
        RejectionDecision: {
            candidate_id: string;
            created_at: string;
            decision: string;
            edits: null;
            id: string;
            namespace: string;
            reason: string;
            reviewer: string;
        };
        RememberCandidateEnvelope: {
            data: components["schemas"]["RememberCandidateResult"];
            pagination: null;
            request_id: string;
            warnings: string[];
        };
        RememberCandidateRequest: {
            /** @default 0.75 */
            confidence?: number;
            evidence_text: string;
            half_life_days?: number | null;
            /** @default 0.5 */
            importance?: number;
            /** @enum {string} */
            memory_type: "correction" | "current_task" | "decision" | "domain_knowledge" | "episodic" | "fact" | "identity" | "inference" | "preference" | "procedure" | "profile" | "project" | "project_state" | "session_summary" | "task" | "temporary_preference" | "tool_usage";
            namespace: string;
            object: string;
            predicate: string;
            /** @enum {string} */
            privacy_level?: "public" | "personal" | "private" | "sensitive" | "secret";
            project_id?: string | null;
            scope?: {
                [key: string]: unknown;
            } | null;
            session_id?: string | null;
            source_type?: string;
            subject: string;
            title?: string | null;
            trust_level?: string;
            /**
             * @default candidate
             * @constant
             */
            write_mode?: "candidate";
        } & {
            [key: string]: unknown;
        };
        RememberCandidateResult: {
            candidate: components["schemas"]["CandidateClaim"];
            /** @constant */
            write_mode: "candidate";
        };
        ResponseEnvelope: {
            data: unknown;
            pagination?: Record<string, never> | null;
            request_id: string;
            warnings: string[];
        };
        RetrievalResult: {
            claim_id: string;
            confidence_base: number;
            confidence_effective: number;
            conflict_ids: string[];
            created_at: string;
            evidence_ids: string[];
            importance: number;
            last_verified_at: string | null;
            lexical_score: number;
            memory_type: string;
            namespace: string;
            object: string;
            predicate: string;
            project_ids: string[];
            retrieval_mode: string;
            score: number;
            semantic_score: number;
            status: string;
            subject: string;
            text: string;
        };
        RetrievalResults: components["schemas"]["RetrievalResult"][];
        RetrievalResultsEnvelope: {
            data: components["schemas"]["RetrievalResults"];
            pagination?: null;
            request_id: string;
            warnings: string[];
        };
        RetrieveRequest: {
            /** @default false */
            include_archived?: boolean;
            /** @default false */
            include_disputed?: boolean;
            /** @default 10 */
            limit?: number;
            memory_types?: string[] | null;
            /**
             * @default hybrid
             * @enum {string}
             */
            mode?: "lexical" | "semantic" | "hybrid";
            namespace: string;
            project_id?: string | null;
            /** @default  */
            query?: string;
            session_id?: string | null;
        } & {
            [key: string]: unknown;
        };
        ReviewCandidate: {
            candidate_status: string;
            contradiction_risk: number;
            created_at: string;
            duplicate_risk: number;
            evidence_ids: string[];
            evidence_spans: components["schemas"]["EvidenceSpan"][];
            extraction_run_id: string;
            id: string;
            memory_type: string;
            metadata: {
                [key: string]: unknown;
            };
            namespace: string;
            object: string;
            predicate: string;
            privacy_level: string;
            revision: string;
            subject: string;
            suggested_categories: string[];
            suggested_confidence: number;
            suggested_entities: string[];
            suggested_half_life_days: number | null;
            suggested_importance: number;
            suggested_scope: {
                [key: string]: unknown;
            } | null;
        };
        ReviewCandidateEnvelope: {
            data: components["schemas"]["ReviewCandidate"];
            pagination: null;
            request_id: string;
            warnings: string[];
        };
        ReviewCandidatePageEnvelope: {
            data: components["schemas"]["ReviewCandidate"][];
            pagination: components["schemas"]["ReviewPagination"];
            request_id: string;
            warnings: string[];
        };
        ReviewOutcome: {
            /** @enum {unknown} */
            action: "promote" | "reject";
            applied_at: string;
            audit_id: string;
            candidate_id: string;
            claim_id: string | null;
            decision_id: string;
            operation_id: string;
            result_revision: string;
            reviewed_revision: string;
        };
        ReviewOutcomeEnvelope: {
            data: components["schemas"]["ReviewOutcome"];
            pagination: null;
            request_id: string;
            warnings: string[];
        };
        ReviewPagination: {
            count: number;
            limit: number;
            next_cursor: string | null;
        };
        ReviewRequest: {
            expected_revision: string;
            reason: string;
        };
        ReviewTask: {
            created_at: string;
            description: string;
            due_at: string | null;
            id: string;
            metadata: {
                [key: string]: unknown;
            };
            namespace: string;
            priority: number;
            recommended_action: string | null;
            severity: string;
            status: string;
            target_id: string;
            target_type: string;
            task_type: string;
            title: string;
            updated_at: string;
        };
        SDKRelease: {
            api_contract_version: string;
            id: string;
            language: string;
            metadata: {
                [key: string]: unknown;
            };
            released_at: string | null;
            sdk_name: string;
            sdk_version: string;
            status: string;
        };
        Version: {
            /** @constant */
            api_version: "v1";
            service_identity: string;
            service_version: string;
            software_version: string;
            supported_features: string[];
            supported_profiles: string[];
        };
        VersionEnvelope: {
            data: components["schemas"]["Version"];
            pagination?: null;
            request_id: string;
            warnings: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getAudit: {
        parameters: {
            query?: never;
            header?: {
                "X-Aletheia-Contract"?: "memory-read-v1";
                "X-Request-ID"?: string;
            };
            path: {
                target_id: string;
                target_type: "claim" | "candidate_claim" | "candidate" | "evidence" | "event";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    "Cache-Control"?: "no-store";
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadAuditEnvelope"];
                };
            };
            /** @description Service error envelope */
            400: {
                headers: {
                    "Cache-Control"?: "no-store";
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Service error envelope */
            401: {
                headers: {
                    "Cache-Control"?: "no-store";
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Service error envelope */
            403: {
                headers: {
                    "Cache-Control"?: "no-store";
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Service error envelope */
            404: {
                headers: {
                    "Cache-Control"?: "no-store";
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Service error envelope */
            413: {
                headers: {
                    "Cache-Control"?: "no-store";
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Service error envelope */
            429: {
                headers: {
                    "Cache-Control"?: "no-store";
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Service error envelope */
            500: {
                headers: {
                    "Cache-Control"?: "no-store";
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    getCurrentPrincipal: {
        parameters: {
            query?: never;
            header?: {
                /** @description Correlation ID; printable ASCII up to 200 characters is also returned as a header. */
                "X-Request-ID"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success envelope */
            200: {
                headers: {
                    "Cache-Control"?: "no-store";
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentPrincipalEnvelope"];
                };
            };
            /** @description Service error envelope */
            400: {
                headers: {
                    "Cache-Control"?: "no-store";
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Service error envelope */
            401: {
                headers: {
                    "Cache-Control"?: "no-store";
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Service error envelope */
            403: {
                headers: {
                    "Cache-Control"?: "no-store";
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Service error envelope */
            413: {
                headers: {
                    "Cache-Control"?: "no-store";
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Service error envelope */
            429: {
                headers: {
                    "Cache-Control"?: "no-store";
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Service error envelope */
            500: {
                headers: {
                    "Cache-Control"?: "no-store";
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    getClaim: {
        parameters: {
            query?: never;
            header?: {
                "X-Aletheia-Contract"?: "memory-read-v1";
                "X-Request-ID"?: string;
            };
            path: {
                claim_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    "Cache-Control"?: "no-store";
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClaimEnvelope"];
                };
            };
            /** @description Service error envelope */
            400: {
                headers: {
                    "Cache-Control"?: "no-store";
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Service error envelope */
            401: {
                headers: {
                    "Cache-Control"?: "no-store";
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Service error envelope */
            403: {
                headers: {
                    "Cache-Control"?: "no-store";
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Service error envelope */
            404: {
                headers: {
                    "Cache-Control"?: "no-store";
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Service error envelope */
            413: {
                headers: {
                    "Cache-Control"?: "no-store";
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Service error envelope */
            429: {
                headers: {
                    "Cache-Control"?: "no-store";
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Service error envelope */
            500: {
                headers: {
                    "Cache-Control"?: "no-store";
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    explainClaim: {
        parameters: {
            query?: never;
            header?: {
                "X-Aletheia-Contract"?: "memory-read-v1";
                "X-Request-ID"?: string;
            };
            path: {
                claim_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    "Cache-Control"?: "no-store";
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadClaimExplanationEnvelope"];
                };
            };
            /** @description Service error envelope */
            400: {
                headers: {
                    "Cache-Control"?: "no-store";
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Service error envelope */
            401: {
                headers: {
                    "Cache-Control"?: "no-store";
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Service error envelope */
            403: {
                headers: {
                    "Cache-Control"?: "no-store";
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Service error envelope */
            404: {
                headers: {
                    "Cache-Control"?: "no-store";
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Service error envelope */
            413: {
                headers: {
                    "Cache-Control"?: "no-store";
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Service error envelope */
            429: {
                headers: {
                    "Cache-Control"?: "no-store";
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Service error envelope */
            500: {
                headers: {
                    "Cache-Control"?: "no-store";
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    getCompatibility: {
        parameters: {
            query?: {
                /** @description Legacy truthy spellings 1, true, yes, on are accepted; other supplied values are false. */
                include_plugins?: boolean;
                /** @description Legacy truthy spellings 1, true, yes, on are accepted; other supplied values are false. */
                include_sdks?: boolean;
                /** @description Legacy truthy spellings 1, true, yes, on are accepted; other supplied values are false. */
                include_runtime?: boolean;
            };
            header?: {
                /** @description Correlation ID; printable ASCII up to 200 characters is also returned as a header. */
                "X-Request-ID"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success envelope */
            200: {
                headers: {
                    "Cache-Control"?: "no-store";
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompatibilityReportEnvelope"];
                };
            };
            /** @description Service error envelope */
            400: {
                headers: {
                    "Cache-Control"?: "no-store";
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Service error envelope */
            401: {
                headers: {
                    "Cache-Control"?: "no-store";
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Service error envelope */
            403: {
                headers: {
                    "Cache-Control"?: "no-store";
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Service error envelope */
            413: {
                headers: {
                    "Cache-Control"?: "no-store";
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Service error envelope */
            429: {
                headers: {
                    "Cache-Control"?: "no-store";
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Service error envelope */
            500: {
                headers: {
                    "Cache-Control"?: "no-store";
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    createContext: {
        parameters: {
            query?: never;
            header?: {
                "X-Aletheia-Contract"?: "memory-read-v1";
                "X-Request-ID"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContextRequest"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    "Cache-Control"?: "no-store";
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadContextPackEnvelope"];
                };
            };
            /** @description Service error envelope */
            400: {
                headers: {
                    "Cache-Control"?: "no-store";
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Service error envelope */
            401: {
                headers: {
                    "Cache-Control"?: "no-store";
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Service error envelope */
            403: {
                headers: {
                    "Cache-Control"?: "no-store";
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Service error envelope */
            404: {
                headers: {
                    "Cache-Control"?: "no-store";
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Service error envelope */
            413: {
                headers: {
                    "Cache-Control"?: "no-store";
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Service error envelope */
            429: {
                headers: {
                    "Cache-Control"?: "no-store";
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Service error envelope */
            500: {
                headers: {
                    "Cache-Control"?: "no-store";
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    createContextPack: {
        parameters: {
            query?: never;
            header?: {
                "X-Aletheia-Contract"?: "memory-read-v1";
                "X-Request-ID"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContextRequest"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    "Cache-Control"?: "no-store";
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadContextPackEnvelope"];
                };
            };
            /** @description Service error envelope */
            400: {
                headers: {
                    "Cache-Control"?: "no-store";
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Service error envelope */
            401: {
                headers: {
                    "Cache-Control"?: "no-store";
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Service error envelope */
            403: {
                headers: {
                    "Cache-Control"?: "no-store";
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Service error envelope */
            404: {
                headers: {
                    "Cache-Control"?: "no-store";
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Service error envelope */
            413: {
                headers: {
                    "Cache-Control"?: "no-store";
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Service error envelope */
            429: {
                headers: {
                    "Cache-Control"?: "no-store";
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Service error envelope */
            500: {
                headers: {
                    "Cache-Control"?: "no-store";
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    getOverview: {
        parameters: {
            query: {
                namespace: string;
                project_id?: string;
            };
            header?: {
                "X-Aletheia-Contract"?: "memory-read-v1";
                "X-Request-ID"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    "Cache-Control"?: "no-store";
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverviewEnvelope"];
                };
            };
            /** @description Service error envelope */
            400: {
                headers: {
                    "Cache-Control"?: "no-store";
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Service error envelope */
            401: {
                headers: {
                    "Cache-Control"?: "no-store";
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Service error envelope */
            403: {
                headers: {
                    "Cache-Control"?: "no-store";
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Service error envelope */
            404: {
                headers: {
                    "Cache-Control"?: "no-store";
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Service error envelope */
            413: {
                headers: {
                    "Cache-Control"?: "no-store";
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Service error envelope */
            429: {
                headers: {
                    "Cache-Control"?: "no-store";
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Service error envelope */
            500: {
                headers: {
                    "Cache-Control"?: "no-store";
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    getHealth: {
        parameters: {
            query?: never;
            header?: {
                /** @description Correlation ID; printable ASCII up to 200 characters is also returned as a header. */
                "X-Request-ID"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success envelope */
            200: {
                headers: {
                    "Cache-Control"?: "no-store";
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthEnvelope"];
                };
            };
            /** @description Service error envelope */
            400: {
                headers: {
                    "Cache-Control"?: "no-store";
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Service error envelope */
            403: {
                headers: {
                    "Cache-Control"?: "no-store";
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Service error envelope */
            413: {
                headers: {
                    "Cache-Control"?: "no-store";
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Service error envelope */
            429: {
                headers: {
                    "Cache-Control"?: "no-store";
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Service error envelope */
            500: {
                headers: {
                    "Cache-Control"?: "no-store";
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    getOpenApi: {
        parameters: {
            query?: never;
            header?: {
                /** @description Correlation ID; printable ASCII up to 200 characters is also returned as a header. */
                "X-Request-ID"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success envelope */
            200: {
                headers: {
                    "Cache-Control"?: "no-store";
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpenApiDocumentEnvelope"];
                };
            };
            /** @description Service error envelope */
            400: {
                headers: {
                    "Cache-Control"?: "no-store";
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Service error envelope */
            403: {
                headers: {
                    "Cache-Control"?: "no-store";
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Service error envelope */
            413: {
                headers: {
                    "Cache-Control"?: "no-store";
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Service error envelope */
            429: {
                headers: {
                    "Cache-Control"?: "no-store";
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Service error envelope */
            500: {
                headers: {
                    "Cache-Control"?: "no-store";
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    getReadiness: {
        parameters: {
            query?: never;
            header?: {
                /** @description Correlation ID; printable ASCII up to 200 characters is also returned as a header. */
                "X-Request-ID"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success envelope */
            200: {
                headers: {
                    "Cache-Control"?: "no-store";
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessEnvelope"];
                };
            };
            /** @description Service error envelope */
            400: {
                headers: {
                    "Cache-Control"?: "no-store";
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Service error envelope */
            403: {
                headers: {
                    "Cache-Control"?: "no-store";
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Service error envelope */
            413: {
                headers: {
                    "Cache-Control"?: "no-store";
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Service error envelope */
            429: {
                headers: {
                    "Cache-Control"?: "no-store";
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Service error envelope */
            500: {
                headers: {
                    "Cache-Control"?: "no-store";
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    rememberCandidate: {
        parameters: {
            query?: never;
            header: {
                "X-Aletheia-Contract": "agent-onboarding-v1";
                "Idempotency-Key": string;
                "X-Request-ID"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RememberCandidateRequest"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    "Cache-Control"?: "no-store";
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RememberCandidateEnvelope"];
                };
            };
            /** @description Creation/service error */
            400: {
                headers: {
                    "Cache-Control"?: "no-store";
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Creation/service error */
            401: {
                headers: {
                    "Cache-Control"?: "no-store";
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Creation/service error */
            403: {
                headers: {
                    "Cache-Control"?: "no-store";
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Creation/service error */
            404: {
                headers: {
                    "Cache-Control"?: "no-store";
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Creation/service error */
            409: {
                headers: {
                    "Cache-Control"?: "no-store";
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Creation/service error */
            413: {
                headers: {
                    "Cache-Control"?: "no-store";
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Creation/service error */
            429: {
                headers: {
                    "Cache-Control"?: "no-store";
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Creation/service error */
            500: {
                headers: {
                    "Cache-Control"?: "no-store";
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Creation/service error */
            503: {
                headers: {
                    "Cache-Control"?: "no-store";
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    retrieveMemory: {
        parameters: {
            query?: never;
            header?: {
                "X-Aletheia-Contract"?: "memory-read-v1";
                "X-Request-ID"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RetrieveRequest"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    "Cache-Control"?: "no-store";
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RetrievalResultsEnvelope"];
                };
            };
            /** @description Service error envelope */
            400: {
                headers: {
                    "Cache-Control"?: "no-store";
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Service error envelope */
            401: {
                headers: {
                    "Cache-Control"?: "no-store";
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Service error envelope */
            403: {
                headers: {
                    "Cache-Control"?: "no-store";
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Service error envelope */
            404: {
                headers: {
                    "Cache-Control"?: "no-store";
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Service error envelope */
            413: {
                headers: {
                    "Cache-Control"?: "no-store";
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Service error envelope */
            429: {
                headers: {
                    "Cache-Control"?: "no-store";
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Service error envelope */
            500: {
                headers: {
                    "Cache-Control"?: "no-store";
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    searchMemory: {
        parameters: {
            query?: never;
            header?: {
                "X-Aletheia-Contract"?: "memory-read-v1";
                "X-Request-ID"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RetrieveRequest"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    "Cache-Control"?: "no-store";
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RetrievalResultsEnvelope"];
                };
            };
            /** @description Service error envelope */
            400: {
                headers: {
                    "Cache-Control"?: "no-store";
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Service error envelope */
            401: {
                headers: {
                    "Cache-Control"?: "no-store";
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Service error envelope */
            403: {
                headers: {
                    "Cache-Control"?: "no-store";
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Service error envelope */
            404: {
                headers: {
                    "Cache-Control"?: "no-store";
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Service error envelope */
            413: {
                headers: {
                    "Cache-Control"?: "no-store";
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Service error envelope */
            429: {
                headers: {
                    "Cache-Control"?: "no-store";
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Service error envelope */
            500: {
                headers: {
                    "Cache-Control"?: "no-store";
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    getVersion: {
        parameters: {
            query?: never;
            header?: {
                /** @description Correlation ID; printable ASCII up to 200 characters is also returned as a header. */
                "X-Request-ID"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success envelope */
            200: {
                headers: {
                    "Cache-Control"?: "no-store";
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionEnvelope"];
                };
            };
            /** @description Service error envelope */
            400: {
                headers: {
                    "Cache-Control"?: "no-store";
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Service error envelope */
            403: {
                headers: {
                    "Cache-Control"?: "no-store";
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Service error envelope */
            413: {
                headers: {
                    "Cache-Control"?: "no-store";
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Service error envelope */
            429: {
                headers: {
                    "Cache-Control"?: "no-store";
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Service error envelope */
            500: {
                headers: {
                    "Cache-Control"?: "no-store";
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
}
